import type { Perfume } from './types';

// API 연동 전 임시 향수 데이터
export const mockPerfumes: Perfume[] = [
  {
    id: 1,
    name: 'Chamo',
    brand: 'Tamburins',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.78952.jpg',
    scent_type: ['Floral', 'Musky', 'Aromatic', 'Woody', 'Spicy', 'Fresh', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 2,
    name: 'Homme Intense 2011',
    brand: 'Dior',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.13016.jpg',
    scent_type: ['Floral', 'Musky', 'Aromatic', 'Fruity', 'Woody', 'Earthy/Smoky'],
  },
  {
    id: 3,
    name: 'Santal 33',
    brand: 'Le Labo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.12201.jpg',
    scent_type: ['Woody', 'Earthy/Smoky', 'Floral', 'Spicy'],
  },
  {
    id: 4,
    name: 'Lust',
    brand: 'Lush',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.10806.jpg',
    scent_type: ['Woody', 'Floral', 'Sweet'],
  },
  {
    id: 5,
    name: 'Man In Black',
    brand: 'Bvlgari',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.26358.jpg',
    scent_type: ['Floral', 'Musky', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 6,
    name: 'CK One',
    brand: 'Calvin Klein',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.276.jpg',
    scent_type: ['Green', 'Floral', 'Musky', 'Aromatic', 'Citrus', 'Woody', 'Fresh'],
  },
  {
    id: 7,
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.25324.jpg',
    scent_type: ['Gourmand', 'Floral', 'Fruity', 'Woody', 'Spicy', 'Sweet'],
  },
  {
    id: 8,
    name: 'Eau de Parfum',
    brand: 'Chloé',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.1733.jpg',
    scent_type: ['Fruity', 'Fresh', 'Floral'],
  },
  {
    id: 9,
    name: 'Gentle Night',
    brand: 'Nonfiction',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.66896.jpg',
    scent_type: ['Green', 'Floral', 'Musky', 'Fruity', 'Woody', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 10,
    name: 'Black',
    brand: 'Ferrari',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.792.jpg',
    scent_type: ['Floral', 'Fruity', 'Citrus', 'Woody', 'Spicy', 'Sweet'],
  },
  {
    id: 11,
    name: 'Vintage',
    brand: 'John Varvatos',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.2356.jpg',
    scent_type: ['Green', 'Aromatic', 'Fruity', 'Woody', 'Spicy', 'Fresh', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 12,
    name: 'Guilty',
    brand: 'Gucci',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.9677.jpg',
    scent_type: ['Floral', 'Musky', 'Fruity', 'Woody', 'Citrus', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 13,
    name: 'Black Orchid',
    brand: 'Tom Ford',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.1018.jpg',
    scent_type: ['Gourmand', 'Floral', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 14,
    name: 'Polo',
    brand: 'Ralph Lauren',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.890.jpg',
    scent_type: ['Green', 'Aromatic', 'Woody', 'Fresh', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 15,
    name: 'White Darjeeling',
    brand: 'Tamburins',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.78957.jpg',
    scent_type: ['Green', 'Floral', 'Musky', 'Fruity', 'Woody', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 16,
    name: 'Eclat d’Arpège',
    brand: 'Lanvin',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.988.jpg',
    scent_type: ['Green', 'Floral', 'Musky', 'Fruity', 'Fresh'],
  },
  {
    id: 17,
    name: "L'Eau d'Issey Pour Homme",
    brand: 'Issey Miyake',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.721.jpg',
    scent_type: ['Green', 'Floral', 'Aromatic', 'Citrus', 'Woody', 'Fresh'],
  },
  {
    id: 18,
    name: 'Decadence',
    brand: 'Marc Jacobs',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.31226.jpg',
    scent_type: ['Floral', 'Aromatic', 'Fruity', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 19,
    name: 'Goddess',
    brand: 'Burberry',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.83483.jpg',
    scent_type: ['Gourmand', 'Fresh', 'Floral', 'Sweet'],
  },
  {
    id: 20,
    name: 'Radiant Nectar',
    brand: 'Clean',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.59860.jpg',
    scent_type: ['Floral', 'Musky', 'Fruity', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 21,
    name: 'Uomo Salvatore Ferragamo Signature',
    brand: 'Salvatore Ferragamo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.50797.jpg',
    scent_type: ['Gourmand', 'Aromatic', 'Citrus', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 22,
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.611.jpg',
    scent_type: ['Floral', 'Citrus', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 23,
    name: 'Nomade',
    brand: 'Chloé',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.48434.jpg',
    scent_type: ['Green', 'Floral', 'Fruity', 'Woody', 'Citrus', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 24,
    name: 'Polo Blue',
    brand: 'Ralph Lauren',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.1198.jpg',
    scent_type: ['Green', 'Musky', 'Aromatic', 'Citrus', 'Woody', 'Fresh'],
  },
  {
    id: 25,
    name: 'Legend Spirit',
    brand: 'Montblanc',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.33443.jpg',
    scent_type: ['Floral', 'Musky', 'Aromatic', 'Citrus', 'Woody', 'Fresh'],
  },
  {
    id: 26,
    name: 'Eau Duelle Eau de Toilette',
    brand: 'Diptyque',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.9241.jpg',
    scent_type: ['Floral', 'Aromatic', 'Woody', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 27,
    name: 'Bright Neroli',
    brand: 'Ferrari',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.30258.jpg',
    scent_type: ['Citrus', 'Fresh', 'Floral', 'Aromatic'],
  },
  {
    id: 28,
    name: 'Flower by Kenzo',
    brand: 'Kenzo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.72.jpg',
    scent_type: ['Floral', 'Musky', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 29,
    name: 'Bloom',
    brand: 'Gucci',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.44894.jpg',
    scent_type: ['Musky', 'Green', 'Floral'],
  },
  {
    id: 30,
    name: 'Artisan Pure',
    brand: 'John Varvatos',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.46623.jpg',
    scent_type: ['Green', 'Aromatic', 'Woody', 'Citrus', 'Fresh'],
  },
  {
    id: 31,
    name: 'Changing Constance',
    brand: "Penhaligon's",
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.50256.jpg',
    scent_type: ['Floral', 'Musky', 'Aromatic', 'Woody', 'Spicy', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 32,
    name: 'Another 13',
    brand: 'Le Labo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.10131.jpg',
    scent_type: ['Floral', 'Musky', 'Fruity', 'Woody', 'Spicy'],
  },
  {
    id: 33,
    name: 'F by Ferragamo Black',
    brand: 'Salvatore Ferragamo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.5002.jpg',
    scent_type: ['Green', 'Floral', 'Aromatic', 'Fruity', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 34,
    name: 'Blu Mediterraneo - Mandorlo di Sicilia',
    brand: 'Acqua di Parma',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.1688.jpg',
    scent_type: ['Gourmand', 'Floral', 'Fruity', 'Citrus', 'Spicy', 'Sweet'],
  },
  {
    id: 35,
    name: 'Jimmy Choo Jimmy Choo for women',
    brand: 'Jimmy Choo',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.10573.jpg',
    scent_type: ['Green', 'Floral', 'Fruity', 'Woody', 'Spicy', 'Fresh', 'Sweet', 'Earthy/Smoky'],
  },
  {
    id: 36,
    name: 'Santal Cream',
    brand: 'Nonfiction',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.66895.jpg',
    scent_type: ['Floral', 'Aromatic', 'Fruity', 'Woody', 'Citrus', 'Spicy', 'Fresh', 'Sweet'],
  },
  {
    id: 37,
    name: 'By the Fireplace',
    brand: 'Maison Martin Margiela',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.31623.jpg',
    scent_type: ['Gourmand', 'Floral', 'Musky', 'Woody', 'Spicy', 'Sweet'],
  },
  {
    id: 38,
    name: 'English Pear & Freesia',
    brand: 'Jo Malone London',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.10314.jpg',
    scent_type: ['Green', 'Floral', 'Musky', 'Fruity', 'Woody', 'Fresh', 'Sweet'],
  },
  {
    id: 39,
    name: 'Bleu de Chanel Eau de Parfum',
    brand: 'Chanel',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.25967.jpg',
    scent_type: ['Floral', 'Aromatic', 'Citrus', 'Woody', 'Spicy', 'Fresh', 'Earthy/Smoky'],
  },
  {
    id: 40,
    name: 'Skin',
    brand: 'Clean',
    imageUrl: 'https://fimgs.net/mdimg/perfume-thumbs/375x500.35244.jpg',
    scent_type: ['Gourmand', 'Floral', 'Musky', 'Citrus', 'Fresh', 'Sweet'],
  },
];
